steps:
  - command: .buildkite/scripts/steps/functional/cloud_security_posture.sh
    label: 'Cloud Security Posture Cypress Tests'
    agents:
      enableNestedVirtualization: true
      localSsds: 1
      localSsdInterface: nvme
      machineType: n2-standard-4
    depends_on:
      - build
      - quick_checks
    timeout_in_minutes: 60
    parallelism: 20
    retry:
      automatic:
        - exit_status: '-1'
          limit: 1

  - command: .buildkite/scripts/steps/functional/cloud_security_posture_serverless.sh
    label: 'Cloud Security Posture Cypress Tests on Serverless'
    agents:
      enableNestedVirtualization: true
      localSsds: 1
      localSsdInterface: nvme
      machineType: n2-standard-4
    depends_on:
      - build
      - quick_checks
    timeout_in_minutes: 60
    parallelism: 14
    retry:
      automatic:
        - exit_status: '-1'
          limit: 1